input {
  gelf {
    port => 5000
  }
}

filter {
  # 1. On déballe le JSON envoyé par Python
  if [message] =~ /^\{.*/ {
    json {
      source => "message"
    }

    # 2. Analyse de la phrase métier à l'intérieur du JSON
    # On gère les deux cas : "added to balance" (dépôt) et "withdrawn" (retrait)
    if [message] =~ /added to balance/ {
      grok {
        match => { "message" => "%{NUMBER:amount:float} successfully added to balance. New balance : %{NUMBER:new_balance:float}" }
        add_field => { "operation_type" => "deposit" }
      }
    } else if [message] =~ /withdrawn/ {
      grok {
        match => { "message" => "%{NUMBER:amount:float} successfully withdrawn ! New balance : %{NUMBER:new_balance:float}" }
        add_field => { "operation_type" => "withdrawal" }
      }
    }
  } else {
    # 3. Suppression des logs techniques Uvicorn (200 OK, etc.)
    drop { }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "mybank-logs-%{+YYYY.MM.dd}"
  }
}